name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # This is a special setting that tells the checkout action to fetch the complete Git history. By default, GitHub Actions only fetches the latest commit to save time and space. Setting fetch-depth: 0 is like saying "I want all the commits, not just the latest one."
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Buld Docker image
      run: |
        docker build -t andresmesad09/docker-graphql:0.0.1 .
    
    - name: Push Docker image
      run: |
        docker push andresmesad09/docker-graphql:0.0.1